### ISSUE TITLE
Credit for Build Dependencies?

### ISSUE THREAD

**Issue by redbow-kimee** [creditstxt/credit-license#4]
Should credit be given to build dependencies such as compilers, build tools, code generation frameworks, etc? If so does this credit differ from linked and runtime dependencies? How is this credit given?

**Comment by kemitchell** [comment]
I think so. And I think `master` currently requires it:

> ## Credit
> 
> You must give this software and each contributor credit for contribution to other works, be they goods or services, that you produce or provide using this software.
