### ISSUE TITLE
Why a license and an exception?

### ISSUE THREAD

**Issue by ioistired** [creditstxt/credit-license#6]
In my personal experience, it's hard enough getting people to use my BlueOak licensed software because they're unfamiliar with the license and are unsure if it holds up in court etc. So I feel like creating another young license, when BlueOak + Credit Requirement would do fine, breeds more confusion, not less. Additionally, both the exception and the license have to be maintained, and backports made from the license to the exception (the exception is currently lagging behind the license). Commons Clause does OK without an integrated permissive license.

**Comment by redbow-kimee** [comment]
I've been thinking much the same thing. From what I can tell, credittxt, is largely derived from Blue Oak, anyways. Further, the Blue Oak Council could become the maintainers of their license, and a family of exceptions which are all similarly easy to read and can be combined for various effects.

**Comment by kemitchell** [comment]
I would actually prefer to cut this down to just a license for now, too. I think one Markdown file without any template tags is easier for folks to edit.
